### ISSUE TITLE
Layout on iPad

### ISSUE THREAD

**Issue by Jinjiang** [mio3io/cr-vue#1]
![ec12070c-90a7-4308-9f9c-36ec098ac723](https://user-images.githubusercontent.com/206848/40899338-08e8f6a4-67f9-11e8-9cf4-7c1f486b8dd3.png)
The sidebar seems too width on iPad.
Anyway this website is so cute with VuePress 👍

**Comment by kazupon** [comment]
@mio3io 
iPadでレイアウトが崩れる問題があるようです。

@Jinjiang 
Thank you for your reporting!

**Comment by mio3io** [comment]
ありがとうございます！
見出し文字が長いため、安直に幅を広げたのが良くなかったようです。
CSS 調整します。

@kazupon @Jinjiang 
Thank you! I will fix this later.
