### ISSUE TITLE
84ページのlistj.sonを読み込もうとしたんですがエラーが出てます.

### ISSUE THREAD

**Issue by teamoo24** [mio3io/cr-vue#10]
from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
のようなエラーが出てますが解決できてません。。。
これに関する回答を見ても出ませんかaxiosに関する例題ってないでしょうか？

**Comment by mio3io** [comment]
https://cr-vue.mio3io.com/guide/chapter2.html#%E5%A4%96%E9%83%A8%E3%81%8B%E3%82%89%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B
お読みいただきありがとうございます😃
こちらの TIP をご覧ください。
