### ISSUE TITLE
スロットが適している場面

### ISSUE THREAD

**Issue by mira-q** [mio3io/cr-vue#11]
何度もすみません、スロットについて教えてください。
スロットでできることは、普通のコンポーネントのpropsを使ってもできると思うのですが、どのような場合にスロットを使うのが良いのでしょうか。
P169の最初のパラグラフの説明が答えなのかのしれませんが、いまいち理解できず...。
よろしくお願いします。

**Comment by mio3io** [comment]
お読みいただきありがとうございます😃
このへんは主観ですが、マークアップを親側で決めたい場合にスロットを使用するとよいかなと思います。コンポーネント側ですべてをやろうとすると、`v-if` などで複雑になってしまいがちなので。
Element UI などのUIキット系のソースコードを見てみると結構多用されているので、参考になるかもしれません。

https://github.com/ElemeFE/element/blob/dev/packages/dropdown/src/dropdown-menu.vue

**Comment by mira-q** [comment]
なるほどー。
Element UIのリンクを見て理解が深まりました。
ありがとうございました。
