### ISSUE TITLE
CHAPTER3-section14のセレクトボックス複数選択の場合

### ISSUE THREAD

**Issue by NERO06** [mio3io/cr-vue#13]
P111ページの複数選択のセレクトボックスですが、複数選択できないです。サポートページのDEMO画面と同じように表示されてはおるのですが、DEMO画面でも私の実行環境でも複数選択まではできません。
書籍上だと複数選択できるような記載(AとCを選択している)があるので、どこかおかしいのではと思っています。
サポートページ: https://cr-vue.mio3io.com/guide/chapter3.html#%E3%82%BB%E3%83%AC%E3%82%AF%E3%83%88%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9
お手数お掛け致しますが、よろしくお願いいたします。

**Comment by mio3io** [comment]
お読みいただきありがとうございます！
複数選択のデモはこちらですが、Ctrl/command＋クリックかドラッグで複数選択できませんか？
https://cr-vue.mio3io.com/guide/chapter3.html#%E8%A4%87%E6%95%B0%E8%A6%81%E7%B4%A0-2

よろしければ、OSとブラウザを教えてください🙏

**Comment by NERO06** [comment]
Ctrl/command＋クリックでできました(^^;;
PC版のセレクトボックスの初歩的な使い方を理解できていなかっただけでした...
おさわがせしましてすいませんでした。
