### ISSUE TITLE
p.267 CH8 SEC44 メッセージを更新する src/components/EditForm.vue のソースコードに誤植部分？

### ISSUE THREAD

**Issue by yokoto** [mio3io/cr-vue#15]
https://gyazo.com/1c1c7dfcc6e9e352d3313852f67360b5

`doUpdate(event)` メソッド内の
`store.dispatch('doUpdate', event.target.value)` がそのまま写経したところ動作しなかったため、
`this.$store.dispatch('doUpdate', event.target.value)` が正しいのかなと思います。

お手数ですがご確認お願い致します。

**Comment by mio3io** [comment]
ありがとうございます！
2刷か3刷で修正した部分なのですがそのときミスしてしまったようです。
次刷で修正させていただきます🙏
